### ISSUE TITLE
saga get action params, but generator.prototype is not undefined in testing

### ISSUE THREAD

**Issue by muzidx** [redux-saga/redux-saga#1143]
According to the docs described inside the way to get action params, I get to action params, as follows:

sagas.js
```
export function* checkout(action) {
    const { id, type, xxx } = action
    if (type === 'all') {
        const shop = yield select(selector.shop)
        // todo something ... 
    }
}
```
saga.spec.js  test
```
import test from 'tape'

test('sagas:checkout', t => {
  const generator = checkout()
  t.deepEqual(
    generator.next().value,
    select(selector.shop),
    'must be select .....'
  )
}
```

Has not yet executed to the `const generator = checkout()`, test throw an error, is:
action.type is undefined, why? Through the action passed over the params, will be given in the test error

```
1)  Uncaught error outside test suite:
         Uncaught TypeError: Cannot read property 'type' of undefined
          at checkout$ (mobile/static_resource/cart/sagas/index.js:81:8)
          at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
          at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
          at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
          at Test.<anonymous> (mobile/static_resource/cart/tests/cart.saga.spec.js:116:15)
          at Test.bound [as _cb] (node_modules/tape/lib/test.js:64:32)
          at Test.run (node_modules/tape/lib/test.js:83:10)
          at Test.bound [as run] (node_modules/tape/lib/test.js:64:32)
          at Immediate.next (node_modules/tape/lib/results.js:71:15)
```

**Comment by Andarist** [comment]
The `action` parameter is injected to ur `checkout` automatically if you use it with combination of `takeEvery`, `takeLatest`, `throttle`.

If you run `checkout` manually in ur testing environment you must provide `action` parameter on ur own.

```js
import test from 'tape'

test('sagas:checkout', t => {
  const action = {type: 'checkout', id: '244242.244324', xxx: 'whatever'}
  const generator = checkout(action)
  t.deepEqual(
    generator.next().value,
    select(selector.shop),
    'must be select .....'
  )
}
```

**Comment by muzidx** [comment]
@Andarist thanks, some late. I got it and solved this problem.
