### ISSUE TITLE
Error when using ``all`` on ``yield all([...]);`` (with webpack)

### ISSUE THREAD

**Issue by ortonomy** [redux-saga/redux-saga#1195]
````
"TypeError: __webpack_require__.i(...) is not a function
    at getDashboardMetrics$ (http://localhost:7001/scripts/bundle.cb763cd1.js:116888:96)
    at tryCatch (http://localhost:7001/scripts/bundle.cb763cd1.js:99689:40)
    at Generator.invoke [as _invoke] (http://localhost:7001/scripts/bundle.cb763cd1.js:99923:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:7001/scripts/bundle.cb763cd1.js:99741:21)
    at next (http://localhost:7001/scripts/bundle.cb763cd1.js:98061:27)
    at proc (http://localhost:7001/scripts/bundle.cb763cd1.js:98020:3)
    at runForkEffect (http://localhost:7001/scripts/bundle.cb763cd1.js:98299:16)
    at runEffect (http://localhost:7001/scripts/bundle.cb763cd1.js:98184:577)
    at next (http://localhost:7001/scripts/bundle.cb763cd1.js:98065:9)
    at currCb (http://localhost:7001/scripts/bundle.cb763cd1.js:98138:7)"
````

Thoughts?

**Comment by anshulsahni** [comment]
any update on this I'm facing same problem

**Comment by Andarist** [comment]
What version of the redux-saga do you use? The best way to receive help is to provide a sample repository with the issue reproduced.

**Comment by ortonomy** [comment]
Hi, @Andarist -- I want to provide a sample repository to you, but at the moment, I'm using redux-sagas in a private organization.

I can say to you that we're on v 0.12.1.

**Comment by anshulsahni** [comment]
I faced the issue while using v0.14.0 but I updated it to latest and the current version is v0.15.6 and it's working fine just the version update nothing else. Apologies for replying late.
