### ISSUE TITLE
the command (npm test ) does not work after the command (npm install)

### ISSUE THREAD

**Issue by HP-jackZhang** [redux-saga/redux-saga#1264]
after npm install , warn :  peerDependencies WARNING babel-plugin-annotate-pure-calls@0.2.1 › @babel/plugin-syntax-dynamic-import@^7.0.0-beta.31 requires a peer of @babel/core@7.0.0-beta.32 but @babel/core@7.0.0-beta.31 was installed

after npm test , warn : 
Cannot find module 'babel-plugin-annotate-pure-calls' from

if i switch  @babel/core@7.0.0-beta.31 into @babel/core@7.0.0-beta.32,  there is still a error

**Comment by Andarist** [comment]
This happens after you clone the repository, right? Not when installing the package from npm

**Comment by Andrew1024** [comment]
I guess, the babel-plugin-annotate-pure-calls is installed not via npm repository ![alt text](http://dl3.joxi.net/drive/2017/11/21/0020/0140/1372300/00/e89855994f.jpg "Here I installed it right myself").

But still there is another mistake and I think, it is connected to babel-plugin-annotate-pure-calls
```
> cross-env BABEL_ENV=es babel src --out-dir es

src/index.js → dist/redux-saga.min.js...--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|

src/index.js → dist/redux-saga.js...
src\effects.js -> es\effects.js
[!] (babel plugin) TypeError: Cannot read property 'isProgram' of null
src\index.js
TypeError: Cannot read property 'isProgram' of null
    at error (C:\Users\las\Desktop\Projects\redux-saga\node_modules\rollup\dist\rollup.js:185:14)
    at Object.error (C:\Users\las\Desktop\Projects\redux-saga\node_modules\rollup\dist\rollup.js:9469:6)
    at promise.then.previous (C:\Users\las\Desktop\Projects\redux-saga\node_modules\rollup\dist\rollup.js:9478:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3

TypeError: Cannot read property 'isProgram' of null
    at isTopLevel (C:\Users\las\Desktop\Projects\redux-saga\node_modules\babel-plugin-annotate-pure-calls\lib\index.js:58:34)
    at isExecutedDuringInitialization (C:\Users\las\Desktop\Projects\redux-saga\node_modules\babel-plugin-annotate-pure-calls\lib\index.js:62:7)
    at PluginPass.callableExpressionVisitor (C:\Users\las\Desktop\Projects\redux-saga\node_modules\babel-plugin-annotate-pure-calls\lib\index.js:103:8)
    at newFn (C:\Users\las\Desktop\Projects\redux-saga\node_modules\@babel\traverse\lib\visitors.js:223:21)
    at NodePath._call (C:\Users\las\Desktop\Projects\redux-saga\node_modules\@babel\traverse\lib\path\context.js:64:19)
    at NodePath.call (C:\Users\las\Desktop\Projects\redux-saga\node_modules\@babel\traverse\lib\path\context.js:38:17)
    at NodePath.visit (C:\Users\las\Desktop\Projects\redux-saga\node_modules\@babel\traverse\lib\path\context.js:95:12)
    at TraversalContext.visitQueue (C:\Users\las\Desktop\Projects\redux-saga\node_modules\@babel\traverse\lib\context.js:139:18)
    at TraversalContext.visitSingle (C:\Users\las\Desktop\Projects\redux-saga\node_modules\@babel\traverse\lib\context.js:98:19)
    at TraversalContext.visit (C:\Users\las\Desktop\Projects\redux-saga\node_modules\@babel\traverse\lib\context.js:180:19)
src\index.js -> es\index.js
```

**Comment by Andrew1024** [comment]
The problem is definitely in babel-plugin-annotate-pure-calls.
![alt text](http://dl4.joxi.net/drive/2017/11/21/0020/0140/1372300/00/b9d71fcf15.jpg "")

**Comment by Andarist** [comment]
Truth to be told - I have no idea what's the problem. I've done fresh installs on my machine and they are working fine. Could you describe exact steps that led to this problem? Also specifying node/npm versions would be helpful.

**Comment by Andrew1024** [comment]
It seems like I got the idea - there was a breaking change in Babel [itself](https://github.com/babel/babel/issues/5828).

And [that line](https://github.com/Andarist/babel-plugin-annotate-pure-calls/blob/a530af9fb411d477ce51a5e3ea81a696c64a779a/src/index.js#L42) uses the old version.

P.S.
npm - 3.10.8
node - 8.6.0

**Comment by Andarist** [comment]
For some reason your npm has downloaded `master` branch from `babel-plugin-annotate-pure-calls` instead of the specified `babel7`.

**Comment by Andrew1024** [comment]
Hmm... The problem was in an old version of `npm`, but `yarn` doesn't work neither.

By the way, we can add [this field](https://docs.npmjs.com/files/package.json#engines) in order to prevent developer mistakes.

**Comment by Andarist** [comment]
I'll release the babel plugin later under other tag than `latest`, should fix problems like this.

**Comment by Andarist** [comment]
I've published the babel plugin to npm and changed redux-saga's dep on it. Things should work for you guys now, let me know if all is ok.

@Arhane unfortunately `engines` field specifies which versions of i.e. npm are capable of installing/using the package as user, not as developer of the package and there is no `devEngines` field :(
