### ISSUE TITLE
problem using multiple eventchannels with redux saga

### ISSUE THREAD

**Issue by kg912** [redux-saga/redux-saga#1327]
Hi, I am trying to dispatch multiple actions after receiving the result of one eventchannel. The action dispatched from ```loginRequest``` should be resolved by ```userData```.
```
export function* loginRequest() {
  let isError = false;

  yield takeEvery('LOGIN_REQUEST', function*(action) {

      const { payload: {loginType, email, password, notification, self} } = action;

      Firebase.login(loginType, { email, password })
        .catch(function(result) {
          const message =
            result && result.message ? result.message : 'Sorry Some error occurs';
          notification('error', message);
          self.setState({
            confirmLoading: false
          });
          isError = true;
        })
        .then(function(result) {
          if (isError) {
            return;
          }
          if (!result || result.message) {
            const message =
              result && result.message
                ? result.message
                : 'Sorry Some error occurs';
            notification('error', message);
            self.setState({
              confirmLoading: false
            });
          } else {
            self.setState({
              visible: false,
              confirmLoading: false
            });

          }
      });


      const authEventsChannel = eventChannel( emit => {
          const unsubscribe = Firebase.auth().onAuthStateChanged( user => {
              if(user) {
                  user.exists = true;
                  emit({user});
              }
              else {
                  user = { exists: false };
                  emit({user});
              }
          });
          // return a function that can be used to unregister listeners when the saga is cancelled
          return unsubscribe;
      });

    // then monitor those events in your saga
      try {
          while (true) {
              const { user, profile } = yield take (authEventsChannel);
              if(user) {
                  if(user.exists == true) {
                      yield put({
                          type: actions.LOGIN_SUCCESS,
                          token: user.uid,
                          profile: user
                      });
	                  yield put({
		                  type: actions.FETCH_USER_DATA,
		                  id: user.uid
	                  });
                      yield put(push('/dashboard'));
                  }
                  else if(user.exists == false) {
                      yield put({
                          type: actions.LOGIN_ERROR
                      })
                  }
                  else {
                      continue;
                  }
              }
          }
        } finally {
          // unregister listener if the saga was cancelled
          if (yield cancelled()) authEventsChannel.close();
        }
    });
}

export function* userData() {
    yield takeEvery(actions.FETCH_USER_DATA, function*(payload) {
    	console.log("PAYLOAD>ID");
    	console.log(payload.id);
	    // first create your eventChannel
	    const dataChannel = eventChannel( emit => {
		    const unsubscribe = firebaseDatabase().ref('/users/' + payload.id).once('value').then(snapshot => {
		    	const info = snapshot.val();
			    emit({ info });
		    });
		    // return a function that can be used to unregister listeners when the saga is cancelled
		    return unsubscribe;
	    });

		// then monitor those events in your saga
	    try {
		    while (true) {
			    const { info } = yield take (dataChannel);
			    // handle auth state
			    yield put({
				    type: actions.USER_DATA,
				    info
			    })
		    }
	    } finally {
		    // unregister listener if the saga was cancelled
		    if (yield cancelled()) dataChannel.close();
	    }
    });

}
```
 The error I'm receiving though is, 
``` 
uncaught at rootSaga at rootSaga 
 at rootSaga 
 at userData 
 at takeEvery 
 at _callee2 
 Error: in eventChannel: subscribe should return a function to unsubscribe
    at eventChannel (http://localhost:3000/static/js/bundle.js:178040:11)
    at _callee2$ (http://localhost:3000/static/js/bundle.js:205677:107)
    at tryCatch (http://localhost:3000/static/js/bundle.js:72755:40)
    at Generator.invoke [as _invoke] (http://localhost:3000/static/js/bundle.js:72989:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/static/js/bundle.js:72807:21)
```
any advice on this matter will be greatly appreciated

**Comment by Andarist** [comment]
I'm not familiar with the Firebase, but it seems that what u return as `unsubscribe` is not a function. To get better help, you'd have to share a repository containing the problem.

**Comment by erikmajlath** [comment]
Hey @kg912 !

Generally speaking if you are not subscribing to changes ( realtime database .on/firestore .onSnapshot ) you do not need to use channels. You can simply
```
const doc = yield firebaseDatabase().ref('/users/' + payload.id).once('value')
```

If you would be reading data using `on` you would need to use channel. In realtime database you can unsubscribe with `off` method as noted there https://firebase.google.com/docs/database/web/read-and-write

> Callbacks are removed by calling the off() method on your Firebase database reference.

Thus channel could look something like this
```
const createUserChannel = userId =>
  eventChannel(emit => {
    const ref = firebaseDatabase().ref(`/users/${userId}`)
    ref.on('value', snap => {
      emit(snap.val())
    })

    const unsubscribe = ref.off()
    return unsubscribe
  })
```

**Comment by neurosnap** [comment]
Closing due to inactivity.  If this is still an issue then please reply and I will reopen and try to help.  Thanks!
