### ISSUE TITLE
npm install fails due to missing rollup.config.js

### ISSUE THREAD

**Issue by vevmesteren** [redux-saga/redux-saga#1363]
npm install redux-saga fails at following 
```
Error: ENOENT: no such file or directory, lstat '/home/me/project/node_modules/redux-saga/rollup.config.js'                                                                     
    at Object.realpathSync (fs.js:1690:15)         
    at runRollup ('/home/me/project/node_modules/redux-saga/node_modules/rollup/bin/rollup:3879:20)                                                                              
    at Object.<anonymous> (/home/me/project/node_modules/redux-saga/node_modules/rollup/bin/rollup:3964:2)                                                                      
    at Module._compile (module.js:649:30)                                                             
    at Object.Module._extensions..js (module.js:660:10)                                               
    at Module.load (module.js:561:32)              
    at tryModuleLoad (module.js:501:12)            
    at Function.Module._load (module.js:493:3)     
    at Function.Module.runMain (module.js:690:10)  
    at startup (bootstrap_node.js:194:16)        

npm ERR! Linux 4.13.0-36-generic                                                                      
npm ERR! argv "/usr/bin/node" "/home/me/project/node_modules/redux-saga/node_modules/npm/bin/npm-cli.js" "run" "build:umd:dev"                                                  
npm ERR! node v9.8.0                                                                                  
npm ERR! npm  v3.7.5                                                                                  
npm ERR! code ELIFECYCLE                                                                              
npm ERR! redux-saga@0.16.0 build:umd:dev: `cross-env BABEL_ENV=es NODE_ENV=development rollup -c -i src/index.js -o dist/redux-saga.js`                                                                     
npm ERR! Exit status 1                                                                                
npm ERR!                                                                                              
npm ERR! Failed at the redux-saga@0.16.0 build:umd:dev script 'cross-env BABEL_ENV=es NODE_ENV=development rollup -c -i src/index.js -o dist/redux-saga.js'.                                                
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redux-saga package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env BABEL_ENV=es NODE_ENV=development rollup -c -i src/index.js -o dist/redux-saga.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redux-saga
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls redux-saga
npm ERR! There is likely additional logging output above.
 
npm ERR! Please include the following file with any support request:                                  
npm ERR!     /home/me/project/node_modules/redux-saga/npm-debug.log       
ERROR: "build:umd:dev" exited with 1.              

npm ERR! Linux 4.13.0-36-generic                   
npm ERR! argv "/usr/bin/node" "/home/me/project/node_modules/redux-saga/node_modules/.bin/npm" "run" "build"                                                                    
npm ERR! node v9.8.0                               
npm ERR! npm  v3.7.5                               
npm ERR! code ELIFECYCLE                           
npm ERR! redux-saga@0.16.0 build: `npm run clean && run-p build:**`                                   
npm ERR! Exit status 1                             
npm ERR!                                           
npm ERR! Failed at the redux-saga@0.16.0 build script 'npm run clean && run-p build:**'.              
npm ERR! Make sure you have the latest version of node.js and npm installed.                          
npm ERR! If you do, this is most likely a problem with the redux-saga package,                        
npm ERR! not with npm itself.                      
npm ERR! Tell the author that this fails on your system:                                              
npm ERR!     npm run clean && run-p build:**       
npm ERR! You can get information on how to open an issue for this project with:                       
npm ERR!     npm bugs redux-saga                   
npm ERR! Or if that isn't available, you can get their info via:                                      
npm ERR!     npm owner ls redux-saga               
npm ERR! There is likely additional logging output above.                                             

npm ERR! Please include the following file with any support request:                                  
npm ERR!     /home/me/project/kol/node_modules/redux-saga/npm-debug.log       
npm ERR! code ELIFECYCLE                           
npm ERR! errno 1                                   
npm ERR! redux-saga@0.16.0 prepare: `npm run build`
npm ERR! Exit status 1                             
npm ERR!                                           
npm ERR! Failed at the redux-saga@0.16.0 prepare script.                                              
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.    
 
```

yarn install passes

**Comment by Andarist** [comment]
How do you install `redux-saga`? I don't think `prepare` should run if you install the package from npm
