### ISSUE TITLE
Function call in generator, generate error, while running test

### ISSUE THREAD

**Issue by revelict** [redux-saga/redux-saga#1386]
Hi,
When i'm running tests i have console error:
```javascript
console.error node_modules\redux-saga\lib\internal\utils.js:240
      uncaught at globalSagas at globalSagas
       at watch
       TypeError: __generator is not a function
          at watch (D:\...\...\...\...\...\...\...\....sagas.tsx:85:12)
          at createTaskIterator (D:\...\...\...\...\node_modules\redux-saga\lib\internal\proc.js:157:17)
          at runForkEffect (D:\...\...\...\...\node_modules\redux-saga\lib\internal\proc.js:561:24)
          at runEffect (D:\...\...\...\...\node_modules\redux-saga\lib\internal\proc.js:446:544)
          at D:\...\...\...\...\node_modules\redux-saga\lib\internal\proc.js:655:14
          at Array.forEach (<anonymous>)
          at runAllEffect (D:\...\...\...\...\node_modules\redux-saga\lib\internal\proc.js:654:10)
          at runEffect (D:\...\...\...\...\node_modules\redux-saga\lib\internal\proc.js:446:249)
          at next (D:\...\...\...\...\node_modules\redux-saga\lib\internal\proc.js:326:9)
          at proc (D:\...\...\...\...\node_modules\redux-saga\lib\internal\proc.js:281:3)
          at runSaga (D:\...\...\...\...\node_modules\redux-saga\lib\internal\runSaga.js:59:33)
          at Object.<anonymous> (D:\...\...\...\...\...\store\Store.tsx:27:16)
          at Runtime._execModule (D:\...\...\...\...\node_modules\jest-runtime\build\index.js:448:13)
          at Runtime.requireModule (D:\...\...\...\...\node_modules\jest-runtime\build\index.js:265:14)
          at Runtime.requireModuleOrMock (D:\...\...\...\...\node_modules\jest-runtime\build\index.js:337:19)
          at Object.<anonymous> (D:\...\...\...\...\...\...\...\i18next.tsx:5:1)
          at Runtime._execModule (D:\...\...\...\...\node_modules\jest-runtime\build\index.js:448:13)
          at Runtime.requireModule (D:\...\...\...\...\node_modules\jest-runtime\build\index.js:265:14)
          at Runtime.requireModuleOrMock (D:\...\...\...\...\node_modules\jest-runtime\build\index.js:337:19)
          at Object.<anonymous> (D:\...\...\...\...\...\...\...\....sagas.tsx:10:1)
          at Runtime._execModule (D:\...\...\...\...\node_modules\jest-runtime\build\index.js:448:13)
          at Runtime.requireModule (D:\...\...\...\...\node_modules\jest-runtime\build\index.js:265:14)
          at Runtime.requireModuleOrMock (D:\...\...\...\...\node_modules\jest-runtime\build\index.js:337:19)
          at Object.<anonymous> (D:\...\...\...\...\...\__tests__\...\...\....sagas.test.tsx:2:1)
          at Runtime._execModule (D:\...\...\...\...\node_modules\jest-runtime\build\index.js:448:13)
          at Runtime.requireModule (D:\...\...\...\...\node_modules\jest-runtime\build\index.js:265:14)
          at D:\...\...\...\...\node_modules\jest-jasmine2\build\index.js:114:13
          at Generator.next (<anonymous>)
          at step (D:\...\...\...\...\node_modules\jest-jasmine2\build\index.js:144:191)
          at D:\...\...\...\...\node_modules\jest-jasmine2\build\index.js:144:437
          at new Promise (<anonymous>)
          at D:\...\...\...\...\node_modules\jest-jasmine2\build\index.js:144:99
          at jasmine2 (D:\...\...\...\...\node_modules\jest-jasmine2\build\index.js:122:17)
          at D:\...\...\...\...\node_modules\jest-runner\build\run_test.js:73:28
          at Generator.next (<anonymous>)
          at step (D:\...\...\...\...\node_modules\jest-runner\build\run_test.js:147:191)
          at D:\...\...\...\...\node_modules\jest-runner\build\run_test.js:147:361
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
```
```javascript
export function* watch() {
    yield all([
        yield takeLatest(...),
        yield takeLatest(...),
        yield takeLatest(...)
    ]);
}
```
```javascript
export function* get(action) {
     // function
    call(someFunction,args); 
    yield put(getSuccess());
}
```
```javascript
export const someFunction= (args) => {    
};
```

when i remove "someFunction" call everything is ok.
if "someFunction" is generator everything is ok.

tests:
```javascript
describe('Method: get', () => {
       it('should load', () => { 
            const gen = get(action);     
            expect(gen.next().value).toEqual(put(getSuccess()));
            expect(gen.next().done).toBe(true);          
       });
});
```

**Comment by Andarist** [comment]
Your report is unfortunately unreadable. Could you reformat it?

**Comment by shinima** [comment]
This is a configuration error in your tslint.json. You are setting `--noEmitHelpers` to `true` in [compiler options](https://www.typescriptlang.org/docs/handbook/compiler-options.html) but you compile your tsx files into javascript files that require [the __generator helper](https://github.com/Microsoft/tslib/blob/master/docs/generator.md).
