### ISSUE TITLE
How to combine sagas?

### ISSUE THREAD

**Issue by daryn-k** [redux-saga/redux-saga#1544]
[This code](https://github.com/redux-saga/redux-saga/issues/160#issuecomment-308540204) doesn't work. I'm using server side rendering.

sagas/index.js:
```
import { all } from 'redux-saga/effects'
import { newsSagas } from '../news/newsSagas'

export default function* rootSaga() {
  yield all([
    ...newsSagas
  ])
}
```

news/newsSagas.js:
```
import { call, put, takeEvery } from 'redux-saga/effects'
import { MAIN_NEWS_FETCH_REQUESTED, MAIN_NEWS_FETCH_FAILED, MAIN_NEWS_FETCH_SUCCEEDED } from './newsReducers'
import { HEADLINES_FETCH_REQUESTED, HEADLINES_FETCH_FAILED, HEADLINES_FETCH_SUCCEEDED } from './newsReducers'
import api from './newsApi'

function* fetchHeadlines() {
  try {
    const headlines = yield call(api.fetchHeadlines)

    yield put({ type: HEADLINES_FETCH_SUCCEEDED, headlines })
  } catch (e) {
    yield put({ type: HEADLINES_FETCH_FAILED, message: e.message })
  }
}

function* fetchMainNews() {
  try {
    const mainNews = yield call(api.fetchMainNews)

    yield put({ type: MAIN_NEWS_FETCH_SUCCEEDED, mainNews })
  } catch (e) {
    yield put({ type: MAIN_NEWS_FETCH_FAILED, message: e.message })
  }
}

export const newsSagas = [
  takeEvery(HEADLINES_FETCH_REQUESTED, fetchHeadlines),
  takeEvery(MAIN_NEWS_FETCH_REQUESTED, fetchMainNews)
]
```

Error:
```
redux-saga error: uncaught at check
take(patternOrChannel): patternOrChannel is undefined
redux-saga error: uncaught at rootSaga
at rootSaga
 at takeEvery
 Error: take(patternOrChannel): patternOrChannel is undefined
    at check (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\utils.js:45:11)
    at take (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\io.js:65:22)
    at takeEvery (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\sagaHelpers\takeEvery.js:21:50)
    at createTaskIterator (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:157:17)
    at runForkEffect (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:561:24)
    at runEffect (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:446:544)
    at C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:655:14
    at Array.forEach (<anonymous>)
    at runAllEffect (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:654:10)
    at runEffect (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:446:249)
redux-saga error: uncaught at check
take(patternOrChannel): patternOrChannel is undefined
redux-saga error: uncaught at rootSaga
at rootSaga
 at takeEvery
 Error: take(patternOrChannel): patternOrChannel is undefined
    at check (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\utils.js:45:11)
    at take (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\io.js:65:22)
    at takeEvery (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\sagaHelpers\takeEvery.js:21:50)
    at createTaskIterator (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:157:17)
    at runForkEffect (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:561:24)
    at runEffect (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:446:544)
    at C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:655:14
    at Array.forEach (<anonymous>)
    at runAllEffect (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:654:10)
    at runEffect (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:446:249)
redux-saga error: uncaught at rootSaga
TypeError: Cannot read property 'forEach' of null
    at end (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:368:18)
    at Object.abort (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:90:5)
    at runForkEffect (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:574:21)
    at runEffect (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:446:544)
    at C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:655:14
    at Array.forEach (<anonymous>)
    at runAllEffect (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:654:10)
    at runEffect (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:446:249)
    at next (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:326:9)
    at proc (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:281:3)
(node:3748) UnhandledPromiseRejectionWarning: Error: take(patternOrChannel): patternOrChannel is undefined
    at check (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\utils.js:45:11)
    at take (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\io.js:65:22)
    at takeEvery (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\sagaHelpers\takeEvery.js:21:50)
    at createTaskIterator (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:157:17)
    at runForkEffect (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:561:24)
    at runEffect (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:446:544)
    at C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:655:14
    at Array.forEach (<anonymous>)
    at runAllEffect (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:654:10)
    at runEffect (C:\site.dev\react\project\node_modules\redux-saga\lib\internal\proc.js:446:249)
(node:3748) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3748) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


```

**Comment by daryn-k** [comment]
It's my fault. Whatever.

**Comment by AcidRaZor** [comment]
@daryn-k I'm sorry but you have to explain where you went wrong, what you fixed / did to overcome this problem. Not just "it's my fault, whatever"

This is a community effort and having it accessible/indexed on Google, some folk, like myself, can stumble onto an issue that I'm experiencing, that appears to be similar to yours, with less experience than yourself to figure out and/or fix it themselves, like you did.

Would have loved a little bit more information on where you went wrong with your thinking, how you fixed it, and try to do this on my own, but alas, "whatever"...

**Comment by daryn-k** [comment]
AcidRaZor, sorry for that. Now I don't remember what was wrong there. But if you're using redux and saga, I would recommend you don't use them anymore. Because after half year of torment with redux and saga I finally dropped them from my projects. You need to create 4 files (actions, reducers, sagas blah-blah-blah) and write many things to do very very simple thing. Use `graphql`, `react context api`, `react hooks`. Hype around redux missleads people.
