### ISSUE TITLE
babel-plugin-redux-saga cannot read property start of undefined

### ISSUE THREAD

**Issue by royipressburger** [redux-saga/redux-saga#1742]
#### Description of the bug/issue
Hi, 

I just updated to version `1.0.0` from `1.0.0-rc-0`.
Everything is working good until I added the `babel-plugin` then I'm getting exception:
`TypeError: Cannot read property 'start' of undefined`

here is the stactrace:
```
TypeError: Cannot read property 'start' of undefined
    at calcLocation (/Users/project/node_modules/babel-plugin-redux-saga/src/index.js:57:26)
    at PluginPass.FunctionExpression (/Users/project/node_modules/babel-plugin-redux-saga/src/index.js:116:26)
    at newFn (/Users/project/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/Users/project/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/project/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/project/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/project/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/Users/project/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/Users/project/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/Users/project/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/Users/project/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/Users/project/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/Users/project/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/Users/project/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/Users/project/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/Users/project/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:95:18)
```

#### Steps to reproduce the bug/issue

for me it was just to add the `babel-plugin-redux-saga`.
removing it just works.

here is my babel file:

```js
module.exports = {
  presets: [
    ['@babel/env', { modules: false }],
    '@babel/react',
  ],
  plugins: [
    'babel-plugin-redux-saga',
    '@babel/syntax-dynamic-import',
    '@babel/plugin-proposal-export-namespace-from',
    'babel-plugin-styled-components',
    'react-hot-loader/babel',
    '@babel/plugin-proposal-class-properties',
    ['transform-imports', {
      ramda: {
        transform: importName => `ramda/es/${importName}`,
        preventFullImport: true,
      },
    }],
  ],
  env: {
    test: {
      presets: [
        ['@babel/env'],
        '@babel/react',
      ],
      plugins: [
        'babel-plugin-styled-components',
      ],
    },
  },
};
```

**Comment by Andarist** [comment]
Thanks for the report! Could you prepare a repro case? It's hard to debug this without sample code which crashes when being transformed.

**Comment by royipressburger** [comment]
Hi @Andarist I tried to create a blank project and add saga to see if it happens, but it does not. 
Im looking on it a bit more now,

**Comment by royipressburger** [comment]
@Andarist Hi again I found the issue, This happens when you have some class function with the `async` prefix.

To reproduce it just clone [this repo](https://github.com/flexdinesh/react-redux-boilerplate).
add the `babel-plugin-redux-saga`
Then under `app/containers/HomePage/HomePage.js` add `async` to the component did mount. and you will see the error

**Comment by restrry** [comment]
should fix https://github.com/redux-saga/redux-saga/pull/1745

**Comment by drewdecarme** [comment]
I'm having the same issue, but it's intermittent. Locally, everything seems to be working fine, even when using React async component lifecycle methods, but for some reason, my CI environment (an internally hosted version of VSTS) doesn't like it.
