### ISSUE TITLE
Problems with testing Redux-Saga in Jest

### ISSUE THREAD

**Issue by vasilii-kovalev** [redux-saga/redux-saga#1804]
I have two questions actually, related to Redux-Saga.
I've created [this demo on Codesandbox](https://codesandbox.io/s/3qvrvm72qq).

1. When testing containers, state (and all props related to redux) is "undefined", but the app works as expected. Am I configured something wrong or it's problem with Jest?
2. Sagas' tests passed in the demo without any warnings, but locally I can see such ones:
<details>
 <summary>Warnings</summary>

    src/store/sagas/data/__tests__/index.test.js
    ● Console
    console.error node_modules/@redux-saga/core/dist/chunk-774a4f38.js:104
      TypeError: Cannot read property 'buildType' of undefined
          at dataSagas (D:\Projects\Template_React_with_Redux\src\store\sagas\data\index.js:40:48)
          at dataSagas.next (<anonymous>)
          at next (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1155:27)
          at proc (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1106:3)
          at D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:589:17
          at immediately (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:60:12)
          at runForkEffect (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:588:3)
          at runEffect (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1202:7)
          at digestEffect (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1269:5)
          at D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:677:5
          at Array.forEach (<anonymous>)
          at runAllEffect (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:676:8)
          at runEffect (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1202:7)
          at digestEffect (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1269:5)
          at next (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1159:9)
          at proc (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1106:3)
          at D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1365:16
          at immediately (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:60:12)
          at runSaga (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1364:10)
          at Function.sagaMiddleware.run (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1425:25)
          at Object.<anonymous> (D:\Projects\Template_React_with_Redux\src\store\index.js:28:16)
          at Runtime._execModule (D:\Projects\Template_React_with_Redux\node_modules\jest-runtime\build\index.js:694:13)
          at Runtime.requireModule (D:\Projects\Template_React_with_Redux\node_modules\jest-runtime\build\index.js:376:14)
          at Runtime.requireModuleOrMock (D:\Projects\Template_React_with_Redux\node_modules\jest-runtime\build\index.js:463:19)
          at Object.<anonymous> (D:\Projects\Template_React_with_Redux\src\store\sagas\data\index.js:11:14)
          at Runtime._execModule (D:\Projects\Template_React_with_Redux\node_modules\jest-runtime\build\index.js:694:13)
          at Runtime.requireModule (D:\Projects\Template_React_with_Redux\node_modules\jest-runtime\build\index.js:376:14)
          at Runtime.requireModuleOrMock (D:\Projects\Template_React_with_Redux\node_modules\jest-runtime\build\index.js:463:19)
          at Object.<anonymous> (D:\Projects\Template_React_with_Redux\src\store\sagas\data\__tests__\index.test.js:7:33)
          at Runtime._execModule (D:\Projects\Template_React_with_Redux\node_modules\jest-runtime\build\index.js:694:13)
          at Runtime.requireModule (D:\Projects\Template_React_with_Redux\node_modules\jest-runtime\build\index.js:376:14)
          at D:\Projects\Template_React_with_Redux\node_modules\jest-jasmine2\build\index.js:129:13
          at Generator.next (<anonymous>)
          at step (D:\Projects\Template_React_with_Redux\node_modules\jest-jasmine2\build\index.js:170:30)
          at D:\Projects\Template_React_with_Redux\node_modules\jest-jasmine2\build\index.js:189:14
          at new Promise (<anonymous>)
          at D:\Projects\Template_React_with_Redux\node_modules\jest-jasmine2\build\index.js:167:12
          at jasmine2 (D:\Projects\Template_React_with_Redux\node_modules\jest-jasmine2\build\index.js:138:17)
          at D:\Projects\Template_React_with_Redux\node_modules\jest-runner\build\run_test.js:187:24
          at Generator.next (<anonymous>)
          at step (D:\Projects\Template_React_with_Redux\node_modules\jest-runner\build\run_test.js:315:30)
          at D:\Projects\Template_React_with_Redux\node_modules\jest-runner\build\run_test.js:326:15
          at processTicksAndRejections (internal/process/next_tick.js:81:5)
    console.error node_modules/@redux-saga/core/dist/chunk-774a4f38.js:105
      The above error occurred in task dataSagas
          created by rootSaga
      Tasks cancelled due to error:
      rootSaga
      usersSagas

    PASS  src/store/selectors/__tests__/posts.test.js
    PASS  src/api/__tests__/users.test.js
    PASS  src/api/__tests__/posts.test.js
    PASS  src/models/Users/__tests__/index.test.js
    PASS  src/store/sagas/__tests__/rootSaga.test.js
    ● Console

    console.error node_modules/@redux-saga/core/dist/chunk-774a4f38.js:104
      TypeError: Cannot read property 'buildType' of undefined
          at usersSagas (D:\Projects\Template_React_with_Redux\src\store\sagas\users\index.js:45:48)
          at usersSagas.next (<anonymous>)
          at next (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1155:27)
          at proc (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1106:3)
          at D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:589:17
          at immediately (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:60:12)
          at runForkEffect (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:588:3)
          at runEffect (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1202:7)
          at digestEffect (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1269:5)
          at D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:677:5
          at Array.forEach (<anonymous>)
          at runAllEffect (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:676:8)
          at runEffect (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1202:7)
          at digestEffect (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1269:5)
          at next (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1159:9)
          at proc (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1106:3)
          at D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1365:16
          at immediately (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:60:12)
          at runSaga (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1364:10)
          at Function.sagaMiddleware.run (D:\Projects\Template_React_with_Redux\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1425:25)
          at Object.<anonymous> (D:\Projects\Template_React_with_Redux\src\store\index.js:28:16)
          at Runtime._execModule (D:\Projects\Template_React_with_Redux\node_modules\jest-runtime\build\index.js:694:13)
          at Runtime.requireModule (D:\Projects\Template_React_with_Redux\node_modules\jest-runtime\build\index.js:376:14)
          at Runtime.requireModuleOrMock (D:\Projects\Template_React_with_Redux\node_modules\jest-runtime\build\index.js:463:19)
          at Object.<anonymous> (D:\Projects\Template_React_with_Redux\src\store\sagas\users\index.js:14:14)
          at Runtime._execModule (D:\Projects\Template_React_with_Redux\node_modules\jest-runtime\build\index.js:694:13)
          at Runtime.requireModule (D:\Projects\Template_React_with_Redux\node_modules\jest-runtime\build\index.js:376:14)
          at Runtime.requireModuleOrMock (D:\Projects\Template_React_with_Redux\node_modules\jest-runtime\build\index.js:463:19)
          at Object.<anonymous> (D:\Projects\Template_React_with_Redux\src\store\sagas\__tests__\rootSaga.test.js:7:37)
          at Runtime._execModule (D:\Projects\Template_React_with_Redux\node_modules\jest-runtime\build\index.js:694:13)
          at Runtime.requireModule (D:\Projects\Template_React_with_Redux\node_modules\jest-runtime\build\index.js:376:14)
          at D:\Projects\Template_React_with_Redux\node_modules\jest-jasmine2\build\index.js:129:13
          at Generator.next (<anonymous>)
          at step (D:\Projects\Template_React_with_Redux\node_modules\jest-jasmine2\build\index.js:170:30)
          at D:\Projects\Template_React_with_Redux\node_modules\jest-jasmine2\build\index.js:189:14
          at new Promise (<anonymous>)
          at D:\Projects\Template_React_with_Redux\node_modules\jest-jasmine2\build\index.js:167:12
          at jasmine2 (D:\Projects\Template_React_with_Redux\node_modules\jest-jasmine2\build\index.js:138:17)
          at D:\Projects\Template_React_with_Redux\node_modules\jest-runner\build\run_test.js:187:24
          at Generator.next (<anonymous>)
          at step (D:\Projects\Template_React_with_Redux\node_modules\jest-runner\build\run_test.js:315:30)
          at D:\Projects\Template_React_with_Redux\node_modules\jest-runner\build\run_test.js:326:15
          at processTicksAndRejections (internal/process/next_tick.js:81:5)
    console.error node_modules/@redux-saga/core/dist/chunk-774a4f38.js:105
      The above error occurred in task usersSagas
          created by rootSaga
      Tasks cancelled due to error:
      rootSaga
</details>

I found out that the modules in the warnings at any point become "undefined". Earlier it was complaining on user sagas, but wasn't complaining on posts ones. Have no idea what's wrong.

* Node.js version: 11.10.1;
* npm version: 6.7.0.

Please, note that I'm using a **.env** file. Maybe it somehow affects the problems.

**Comment by shinima** [comment]
From your demo on Codesanbox, why tests are failing seems NOT related to redux-saga. It seems to be related to jest snapshot, however I'm not familiar with jest snapshot.

---

> Cannot read property 'buildType' of undefined

This error is due to your bundler (e.g. webpack) in the local envoriment. You need to tweak the config to make module-style importing (`import { buildType } from "src/utils/buildType"`) work. You may need [this](https://webpack.js.org/concepts/module-resolution/#module-paths).

**Comment by vasilii-kovalev** [comment]
@shinima
1. If you just log `component.props()` or `component.instance().props`, you can't see any props you are expecting, so, it's not related to jest snapshots as far as I can see.
2. Hmm, are there any differences between locally installed project via CRA or installed one on Codesandbox? Webpack (embedded in CRA) in both cases is the same, isn't it?

**Comment by vasilii-kovalev** [comment]
Closing the issue since I'm not interested in it now.
