### ISSUE TITLE
Can not cancel take effect after race

### ISSUE THREAD

**Issue by Niklv** [redux-saga/redux-saga#1859]
#### Description of the bug/issue
Can not cancel take effect:

```
TypeError: currCb.cancel is not a function
    at Function.cb.cancel (./node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1262:14)
    at ./node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:715:30
    at Array.forEach (<anonymous>)
    at Function.cb.cancel (./node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:714:12)
    at chCbAtKey (./node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:699:12)
    at currCb (./node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1249:7)
```

#### Steps to reproduce the bug/issue

```js

const { runSaga } = require('redux-saga'); // version 1.0.2
const { race, take, delay } = require('redux-saga/effects');

runSaga(
    {
        channel: {
            take() {
                // silent channel
            }
        },
        dispatch() {},
        getState() {}
    },
    function*() {
        yield race({
            t: take('*'),
            d: delay(1000)
        });
    }
);

```

I try read the redux-saga and debug this issue. 
I think error in this file (line 104):
https://github.com/redux-saga/redux-saga/blob/6667d125b9cbc2c65d1c685468c1b2fe1bbdecd1/packages/core/src/internal/effectRunnerMap.js#L85-L106

There are no `takeCb.cancel` implementation.

**Comment by Niklv** [comment]
Ok, i got it. I should define cancel method on `callback` parameter in `take` function.
Another way - use `stdChannel()` and send message to this channel.
