### ISSUE TITLE
When react-native starts up, `'main' module field that could not be resolved` is displayed

### ISSUE THREAD

**Issue by nitaking** [redux-saga/redux-saga#1877]
### Description
It may not be a problem with redux-saga, but it is a question.

Used in react-native.

```
<version>
react-native: 0.59.9
redux-saga: 1.0.2
```

When raising the version of react-native from 0.55.6 to 0.59.9, the following error message occurred at app startup:

```
error: bundling failed: Error: While trying to resolve module `redux-saga` from file` / Users / user2 / code / air-closet / packages / native / src / App.js`, the package `/ Users / user2 / However, this package its module specifies a `main` module field that could not be resolved (` / Users / user2 / code / code / code / air-closet / packages / native / node_modules / redux-saga / package.json` was successfully found. air-closet / packages / native / node_modules / redux-saga / dist / redux-saga-core-npm-proxy.cjs.js`. Indeed, none of these files exist:

  * `/Users/user2/code/air-closet/packages/native/node_modules/redux-saga/dist/redux-saga-core-npm-proxy.cjs.js (.native || .ios.js | .native .js | .js | .ios.json | .native.json | .json | .ios.ts | .native.ts | .ts | .ios.tsx | .native.tsx | .tsx) `
  * `/Users/user2/code/air-closet/packages/native/node_modules/redux-saga/dist/redux-saga-core-npm-proxy.cjs.js/index (.native || .ios.js | .native.js | .js | .ios.json | .native.json | .json | .ios.ts | .native.ts | .ts | .ios.tsx | .native.tsx | .tsx) `
    at ResolutionRequest.resolveDependency (/Users/user2/code/air-closet/packages/native/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js: 65: 15)
    at DependencyGraph.resolveDependency (/Users/user2/code/air-closet/packages/native/node_modules/metro/src/node-haste/DependencyGraph.js: 283: 16)
    at Object.resolve (/Users/user2/code/air-closet/packages/native/node_modules/metro/src/lib/transformHelpers.js: 261: 42)
    at dependencies.map.result (/Users/user2/code/air-closet/packages/native/node_modules/metro/src/DeltaBundler/traverseDependencies.js: 399: 31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/user2/code/air-closet/packages/native/node_modules/metro/src/DeltaBundler/traverseDependencies.js: 396: 18)
    at /Users/user2/code/air-closet/packages/native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/user2/code/air-closet/packages/native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
    at _next (/Users/user2/code/air-closet/packages/native/node_modules/metro/src/DeltaBundler/traverseDependencies.js: 107: 9)
```

The error `node_modules / redux-saga / dist / redux-saga-core-npm-proxy.cjs.js` exists.

![image](https://user-images.githubusercontent.com/10850034/60170620-c5c89b00-9843-11e9-95bf-2ff71500e04e.png)

**Comment by Andarist** [comment]
Seems like an issue with Metro Bundler which is used by React Native. Could you report it over there?

**Comment by nitaking** [comment]
@Andarist 
Thank you!
I will do that ...!
