### ISSUE TITLE
Error building examples

### ISSUE THREAD

**Issue by j1dopeman** [redux-saga/redux-saga#2074]
I run the 4 steps from the readme for building examples:
git clone...
cd redux-saga
yarn
npm test

It returns an error for npm test with:
```
Error: Cannot find module 'c:\Source\other\redux-saga\node_modules\redux-saga\dist\redux-saga-core-npm-proxy.cjs.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:316:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:705:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:969:27)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (c:\Source\other\redux-saga\examples\error-demo\test/sagas.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Module._compile (c:\Source\other\redux-saga\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10) {
  code: 'MODULE_NOT_FOUND',
  path: 'c:\\Source\\other\\redux-saga\\node_modules\\redux-saga\\package.json',
  requestPath: 'redux-saga'
}
error Command failed with exit code 1.
```

**Comment by deanius** [comment]
And it's a different error now, but I noticed the same @j1dopeman today:

```
> @ test /Users/dean.radcliffe/src/redux-saga
> lerna run --parallel test

lerna notice cli v3.17.0
lerna info Executing command in 8 packages: "yarn run test"
async-example: yarn run v1.22.4
cancellable-counter-example: yarn run v1.22.4
error-demo: yarn run v1.22.4
counter-example: yarn run v1.22.4
shopping-cart-example: yarn run v1.22.4
babel-plugin-redux-saga: yarn run v1.22.4
@redux-saga/testing-utils: yarn run v1.22.4
@redux-saga/core: yarn run v1.22.4
cancellable-counter-example: $ cross-env BABEL_ENV=cjs babel-node ./test/sagas.js | tap-spec
async-example: $ cross-env NODE_ENV=test babel-node test/sagas.js | tap-spec
counter-example: $ cross-env NODE_ENV=test babel-node test/sagas.js | tap-spec
shopping-cart-example: $ cross-env NODE_ENV=test babel-node test/sagas.js | tap-spec
error-demo: $ cross-env NODE_ENV=test babel-node test/sagas.js | tap-spec
babel-plugin-redux-saga: $ jest --env=node
@redux-saga/testing-utils: $ yarn test:types && yarn test:jest
@redux-saga/core: $ yarn test:types && yarn test:jest
@redux-saga/testing-utils: $ dtslint types
@redux-saga/core: $ dtslint types
@redux-saga/testing-utils: Installing to /Users/dean.radcliffe/.dts/typescript-installs/2.2...
@redux-saga/core: Installing to /Users/dean.radcliffe/.dts/typescript-installs/2.3...
cancellable-counter-example: Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
shopping-cart-example: Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
async-example: Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
@redux-saga/testing-utils: npm ERR! cb.apply is not a function
@redux-saga/testing-utils: npm ERR! A complete log of this run can be found in:
@redux-saga/testing-utils: npm ERR!     /Users/dean.radcliffe/.npm/_logs/2020-10-02T19_26_36_208Z-debug.log
@redux-saga/testing-utils: Error: Command failed: npm install --ignore-scripts --no-shrinkwrap --no-package-lock --no-bin-links
@redux-saga/testing-utils: npm ERR! cb.apply is not a function
@redux-saga/testing-utils: npm ERR! A complete log of this run can be found in:
@redux-saga/testing-utils: npm ERR!     /Users/dean.radcliffe/.npm/_logs/2020-10-02T19_26_36_208Z-debug.log
@redux-saga/testing-utils:     at ChildProcess.exithandler (child_process.js:303:12)
@redux-saga/testing-utils:     at ChildProcess.emit (events.js:315:20)
@redux-saga/testing-utils:     at maybeClose (internal/child_process.js:1021:16)
@redux-saga/testing-utils:     at Socket.<anonymous> (internal/child_process.js:443:11)
@redux-saga/testing-utils:     at Socket.emit (events.js:315:20)
@redux-saga/testing-utils:     at Pipe.<anonymous> (net.js:674:12)
@redux-saga/testing-utils: error Command failed with exit code 1.
@redux-saga/testing-utils: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
counter-example: Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
@redux-saga/testing-utils: error Command failed with exit code 1.
@redux-saga/testing-utils: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run test exited 1 in '@redux-saga/testing-utils'
lerna ERR! yarn run test stdout:
yarn run v1.22.4
$ yarn test:types && yarn test:jest
$ dtslint types
Installing to /Users/dean.radcliffe/.dts/typescript-installs/2.2...
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run test stderr:
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dean.radcliffe/.npm/_logs/2020-10-02T19_26_36_208Z-debug.log

Error: Command failed: npm install --ignore-scripts --no-shrinkwrap --no-package-lock --no-bin-links
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dean.radcliffe/.npm/_logs/2020-10-02T19_26_36_208Z-debug.log

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
error Command failed with exit code 1.
error Command failed with exit code 1.

lerna ERR! yarn run test exited 1 in '@redux-saga/testing-utils'
lerna WARN complete Waiting for 7 child processes to exit. CTRL-C to exit immediately.
npm ERR! Test failed.  See above for more details.
```

**Comment by neurosnap** [comment]
Closing due to inactivity.  Please feel free to reply if you are still having this issue and I’d be happy to help debug.
