### ISSUE TITLE
Can't resolve '@redux-saga/core' in latest version

### ISSUE THREAD

**Issue by ayxos** [redux-saga/redux-saga#2148]
### Steps to reproduce
on package.json:
...
    "redux-saga": "^1.1.3"
...

`npm i`

#### Description of the bug/issue
```
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve '@redux-saga/core' in '/app/node_modules/redux-saga/dist'
    at /app/node_modules/webpack/lib/Compilation.js:925:10
    at /app/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /app/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /app/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /app/node_modules/neo-async/async.js:2830:7
    at /app/node_modules/neo-async/async.js:6877:13
    at /app/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /app/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:213:14
    at /app/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/app/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /app/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /app/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/app/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /app/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/app/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /app/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
resolve '@redux-saga/core' in '/app/node_modules/redux-saga/dist'
  Parsed request is a module
  using description file: /app/node_modules/redux-saga/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in /app/src/app
        using description file: /app/package.json (relative path: ./src/app)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /app/package.json (relative path: ./src/app/@redux-saga/core)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /app/src/app/@redux-saga/core doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /app/src/app/@redux-saga/core.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /app/src/app/@redux-saga/core.jsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /app/src/app/@redux-saga/core.json doesn't exist
            as directory
              /app/src/app/@redux-saga/core doesn't exist
      looking for modules in /app/node_modules
        using description file: /app/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /app/package.json (relative path: ./node_modules/@redux-saga/core)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /app/node_modules/@redux-saga/core doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /app/node_modules/@redux-saga/core.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /app/node_modules/@redux-saga/core.jsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /app/node_modules/@redux-saga/core.json doesn't exist
            as directory
              /app/node_modules/@redux-saga/core doesn't exist
      /app/node_modules/redux-saga/dist/node_modules doesn't exist or is not a directory
      /app/node_modules/redux-saga/node_modules doesn't exist or is not a directory
      /app/node_modules/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /app/node_modules
        using description file: /app/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /app/package.json (relative path: ./node_modules/@redux-saga/core)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /app/node_modules/@redux-saga/core doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /app/node_modules/@redux-saga/core.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /app/node_modules/@redux-saga/core.jsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /app/node_modules/@redux-saga/core.json doesn't exist
            as directory
              /app/node_modules/@redux-saga/core doesn't exist
```

#### Steps to reproduce the bug/issue

1. try to install the redux-saga dep with "^1.1.3"
...

I have fixed it setting the version to: 1.1.3 (no higher)

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by neurosnap** [comment]
Closing this issue due to inactivity.  Please feel free to reply here and I can reopen to help debug.  Thanks!
