### ISSUE TITLE
TypeError: Cannot assign to read only property 'cont' of object '#<Object>'

### ISSUE THREAD

**Issue by Code-Mythos** [redux-saga/redux-saga#2363]
### Description
I am running into this error when trying to cancel a previously stored task (via fork).

### Steps to reproduce

```
import type { Task } from "redux-saga";

import createSagaMiddleware from "redux-saga";
import {
  all,
  call,
  cancel,
  fork,
  put,
  select,
  spawn,
  takeEvery,
} from "redux-saga/effects";

import { configureStore, createSlice } from "@reduxjs/toolkit";

// Helpers *******************************************************************************
function dummyTask(timeout: number, resolved: boolean) {
  // console.log("Parameters: \n", timeout, resolved);
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      console.log("Parameters: \n", timeout, resolved);

      if (resolved) resolve(true);
      else reject("Rejected.");
    }, timeout);
  });
}

// Types *********************************************************************************
type StateType = { tasks: { [taskId: string]: Task } };

// Create Reducer ************************************************************************
const initialState: StateType = { tasks: {} };

const { actions, reducer } = createSlice({
  name: "ReduxCancelError",

  initialState,

  reducers: {
    started: (state, action) => {},

    addedTask: (state, action) => {
      state.tasks.onlyTask = action.payload.onlyTask;
    },

    terminatedTask: (state, action) => {
      delete state.tasks.onlyTask;
    },

    terminateRequested: (state, action) => {},
  },
});

// Sagas *********************************************************************************
function* startSaga() {
  yield takeEvery(actions.started.type, startSagaHandler);
}
function* startSagaHandler() {
  yield call(terminateSagaHandler);

  const task: Task = yield fork(dummyTask, 750, true);

  yield put(
    actions.addedTask({
      onlyTask: task,
    })
  );
}

function* terminateSaga() {
  yield takeEvery(actions.terminateRequested.type, terminateSagaHandler);
}
function* terminateSagaHandler() {
  const state: StateType = yield select();
  const onlyTask = state.tasks.onlyTask;

  if (!onlyTask) return;

  yield cancel(onlyTask);

  yield put(actions.terminatedTask({}));
}

function* rootSaga() {
  yield all([
    spawn(function* () {
      while (true) {
        try {
          yield call(startSaga);
          break;
        } catch (error) {
          console.error(error);
        }
      }
    }),
    spawn(function* () {
      while (true) {
        try {
          yield call(terminateSaga);
          break;
        } catch (error) {
          console.error(error);
        }
      }
    }),
  ]);
}

const sagaMiddleware = createSagaMiddleware();
const runSaga = sagaMiddleware.run;

// Create Store **************************************************************************
const store = configureStore({
  reducer,
  middleware: [sagaMiddleware],
});
runSaga(rootSaga);

export { store, actions };

```

#### Produce the bug/issue

```
store.dispatch(actions.started({}));
store.dispatch(actions.terminateRequested({}));
```

#### Description of the bug/issue
```
TypeError: Cannot assign to read only property 'cont' of object '#<Object>'
          at Object.task.cont (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:829:17)
          at end (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1016:10)
          at Object.cancel (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:979:7)
          at cancelSingleTask (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:647:18)
          at runCancelEffect (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:659:5)
          at runEffect (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1208:7)
          at digestEffect (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1275:5)
          at next (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1165:9)
          at proc (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1112:3)
          at runCallEffect (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:537:7)
          at runEffect (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1208:7)
          at digestEffect (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1275:5)
          at next (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1165:9)
          at Object.currCb [as cont] (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1255:7)
          at end (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1016:10)
          at Object.task.cont (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:840:11)
          at next (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1174:18)
          at currCb (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1255:7)
          at C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:485:7
          at exec (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:35:5)
          at flush (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:91:5)
          at asap (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:50:5)
          at Object.chan.put (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:379:5)
          at C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\@redux-saga\core\dist\redux-saga-core.dev.cjs.js:1416:17
          at Object.dispatch [as terminate] (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\interfaces\i_Stores\taskManager\taskManagerStore.ts:293:9)
          at Object.terminate (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\interfaces\i_Stores\taskManager\taskManagerStore.test.ts:108:13)
          at Promise.then.completed (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\jest-circus\build\utils.js:293:28)
          at new Promise (<anonymous>)
          at callAsyncCircusFn (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\jest-circus\build\utils.js:226:10)
          at _callCircusTest (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\jest-circus\build\run.js:248:40)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at _runTest (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\jest-circus\build\run.js:184:3)          at _runTestsForDescribeBlock (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\jest-circus\build\run.js:86:9)
          at _runTestsForDescribeBlock (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\jest-circus\build\run.js:81:9)
          at run (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\jest-circus\build\run.js:26:3)      
          at runAndTransformResultsToJestFormat (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapterInit.js:120:21)
          at jestAdapter (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapter.js:79:19)
          at runTestInternal (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\jest-runner\build\runTest.js:367:16)
          at runTest (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\jest-runner\build\runTest.js:444:34)
          at Object.worker (C:\Users\Light\Desktop\Portfolio\Instructions\Sample-Code\next-general-02\node_modules\jest-runner\build\testWorker.js:106:12)
```

**Comment by Code-Mythos** [comment]
The redux itself freezes the task. There is no problem with Redux Saga.
