### ISSUE TITLE
consider using createMockTask from redux-saga/utils

### ISSUE THREAD

**Issue by piuccio** [redux-saga/redux-saga#993]
Hi, I just upgraded `redux-saga` from `0.14.3` to `0.15.3` and this test now fails

```js
/* eslint-disable redux-saga/yield-effects */
import { cancel, take, race } from 'redux-saga/effects';
import { createMockTask } from 'redux-saga/utils';
import { cancelWatchersOnFirstEvent } from '../saga';

describe('cancelWatchers', () => {
  const watcher1 = createMockTask();
  const watcher2 = createMockTask();
  const watchers = [watcher1, watcher2];

  it('cancels all passed watchers after a LOCATION_CHANGE', () => {
    const generator = cancelWatchersOnFirstEvent(watchers);
    expect(generator.next().value).toEqual(
      race({
         [LOCATION_CHANGE]: take(LOCATION_CHANGE),
      }),
    );
    expect(generator.next().value).toEqual(
      [cancel(watcher1), cancel(watcher2)]
    );
  });
});
```

The message says

```
 * cancelWatchers › cancels all passed watchers after a LOCATION_CHANGE

    cancel(task): argument 0 is not a valid Task object 
    (HINT: if you are getting this errors in tests, consider using createMockTask from redux-saga/utils)
      
      at check (node_modules/redux-saga/lib/internal/utils.js:45:11)
      at cancel (node_modules/redux-saga/lib/internal/io.js:197:22)
      at node_modules/redux-saga/lib/internal/io.js:191:14
      at Array.map (native)
      at cancel (node_modules/redux-saga/lib/internal/io.js:190:22)
      at Array.map (native)
      at cancelWatchersOnFirstEvent$ (app/utils/saga.js:30:107)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at Object.<anonymous> (app/utils/tests/saga.test.js:21:22)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

The source code of that `cancelWatchersOnFirstEvent` is

```js
import { LOCATION_CHANGE } from 'react-router-redux';
import { cancel, take, race } from 'redux-saga/effects';

/**
 * Cancels all passed watchers after the first event fires
 *
 * @param watchers List of watchers to cancel
 * @param events List of events to
 */
export function* cancelWatchersOnFirstEvent(watchers, events = [LOCATION_CHANGE]) {
  const eventHash = events.reduce((result, event) => Object.assign({ [event]: take(event) }, result), {}); // eslint-disable-line redux-saga/yield-effects
  yield race(eventHash); // eslint-disable-line redux-saga/no-yield-in-race
  yield watchers.map(cancel);
}
```

**Comment by Andarist** [comment]
It's because we have started to accept multiple task in cancel effects.

So you can use it now like this:
```js
yield cancel(...watchers)
```
to make it work in ur original example you would have to cap ur `map`, its because map used liek that will pass to the `cancel` its all 3 iteratee arguments, so - element, index, array. And they all are being interpreted by `cancel` now as tasks.

So you can also fix ur code like this
```js
yield watchers.map(watcher => cancel(watcher))
// or even better in 0.15
yield all(watchers.map(watcher => cancel(watcher)))
```

**Comment by piuccio** [comment]
cool that works, thank you
